### ISSUE TITLE
Кнопка "Присоединиться" отображается у только что созданого события

### ISSUE THREAD

**Issue by xctmaf** [edele/goeat#7]

**Comment by xctmaf** [comment]
по нажатию на нее, кстати, ничего не происходит, что вполне логично

**Comment by edele** [comment]
Происходит. Просто на рендер это не влияет)

**Comment by edele** [comment]
@xctmaf, решил проблему с помощью реста — возвращаю с сервера нормализованное состояние события в ответ на сабмит и устанавливаю его в модель на клиенте.

Почему-то, когда контролирую и фронт и бэк — хочется такие вещи делать на стороне бэка, а не фронта.

На серве состояние железобетоннее. На фронте приходится фантазировать и предполагать.
